# Generated by Django 4.2.3 on 2023-07-29 19:33

from django.db import migrations, models
import retro_cars.restoration_shops.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(validators=[retro_cars.restoration_shops.validators.valid_phone_number_validator])),
                ('email', models.EmailField(max_length=254)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RestorationShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_image_url', models.URLField()),
                ('offer', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
